personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[sandbox_workspace_write]
network_access = true

[features]
memories = true

[plugins."github@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[projects."/Users/jxck/develop/jxck.io"]
trust_level = "trusted"

[projects."/Users/jxck/develop/cdt-toolkit"]
trust_level = "trusted"

[projects."/home/jxck/dotfiles"]
trust_level = "trusted"

[projects."/Users/jxck/develop/mozaic.fm"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-04-30T06:25:42Z"
source_type = "local"
source = "/Users/jxck/.codex/.tmp/bundled-marketplaces/openai-bundled"
