[tools]
node = "latest"
deno = "latest"
bun = "latest"
go = "latest"
usage = "latest"
rust = "latest"
pnpm = "latest"
# ruby = "latest" use brew
# gcloud = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@jxck/markdown" = "latest"
"npm:difit" = "latest"
"npm:npm-check-updates" = "latest"

[settings]
idiomatic_version_file_enable_tools = []