# Global

## vi キーバインド
set-window-option -g mode-keys vi

## prefix を C-s に変更
set-option -g prefix C-s

## マウスサポート (ペイン選択/リサイズ/スクロール)
set -g mouse on

## vim の FocusGained/FocusLost を tmux 内でも有効にする
set -g focus-events on

## 256色ターミナル
set-option -g default-terminal "tmux-256color"

## スクロールバッファ
set-option -g history-limit 100000

## C-s+C-r: tmux.conf リロード
bind C-r source-file ~/.tmux.conf

## C-S+C-a: prefix をアプリに送る (tmux をネストした時用)
bind C-a send-prefix


# ステータスライン

## 基本色
set -g status-bg black
set -g status-fg white

## 左部: [ウィンドウ番号-ペイン番号] prefix 押下時に反転
set -g status-left '#{?client_prefix,#[reverse],}#[fg=cyan,bold][#I-#P]#[default]'
set -g status-left-length 20

## 右部: [日時] prefix 押下時に反転
set -g status-right '#{?client_prefix,#[reverse],}#[fg=cyan,bold][%Y/%m/%d(%a)%H:%M]#[default]'
set -g message-style fg="white","bold",bg="red"

# OS 別設定 (コピー操作等)
if-shell "uname | grep -q  Linux" "source-file ~/dotfiles/tmux/linux.tmux.conf" ""
if-shell "uname | grep -q Darwin" "source-file ~/dotfiles/tmux/darwin.tmux.conf" ""


# ウィンドウ操作

## C-s C-n でも C-s n でも次へ
unbind C-n
bind C-n next-window

## C-s C-p でも C-s p でも前へ
unbind C-p
bind C-p previous-window ## 前へ

## C-s C-c でも C-s c でも生成
unbind C-c
bind C-c new-window -c "#{pane_current_path}"
unbind c
bind c new-window -c "#{pane_current_path}"


# ペイン

## 分割(0~9 は window の移動だが使わないので上書き)
unbind 0
unbind 1
unbind 2
unbind 3
unbind 4
unbind 8
unbind 9
bind 0 break-pane                                      # ペインをウィンドウに切り出す
bind 1 split-window -h -c "#{pane_current_path}"       # 右に分割
bind 2 split-window -v -c "#{pane_current_path}"       # 下に分割
bind 3 split-window -h -b -c "#{pane_current_path}"    # 左に分割
bind 4 split-window -v -b -c "#{pane_current_path}"    # 上に分割
bind 8 swap-pane -t :.0 \; select-layout main-vertical # 現在のペインを左メインにする
bind 9 kill-pane                                       # ペインを閉じる (確認なし)

## リサイズ (リピート可)
bind -r C-h resize-pane -L 6
bind -r C-l resize-pane -R 6
bind -r C-j resize-pane -D 6
bind -r C-k resize-pane -U 6

## 入れ替え (リピート可)
unbind C-o
bind -r C-o swap-pane -D

## 移動 (vi 風)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
