FROM base
RUN apt update
RUN apt install -y openssh-server
RUN apt install wget

RUN mkdir /var/run/sshd

RUN mkdir /root/.ssh
RUN chmod 700 /root/.ssh
RUN cd /root/.ssh
RUN wget https://github.com/Jxck.keys
RUN mv Jxck.keys authorized_keys
RUN cat authorized_keys
RUN chmod 600 authorized_keys

RUN sudo sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

CMD /usr/sbin/sshd -D
EXPOSE 22
