alias bundle-install="bundle install --path vendor/bundle"
alias rake="bundle exec rake"
#alias ruby="bundle exec ruby"
alias rails="bundle exec rails"
alias guard="bundle exec guard"
alias r="rails"
alias rs="unicorn -p 3000"
